### ISSUE TITLE
支付宝小程序 一引用sensorsdata.js 真机界面就显示不出来

### ISSUE THREAD

**Issue by YYBT** [sensorsdata/sa-sdk-alipaymini#2]
import sensors from './utils/sensorsdata.js';

模拟器上好的，就是真机上不行
真机报错
[WORKER] onerror ["TypeError: undefined is not an object (evaluating 'l.newPage')",null,null,null,null]

**Comment by wangzhzh** [comment]
请问你是个人还是神策的客户？

**Comment by YYBT** [comment]
客户

**Comment by wangzhzh** [comment]
请问是哪个客户？

**Comment by YYBT** [comment]
杭州场景鹿

**Comment by wangzhzh** [comment]
好的，我们已安排相关工程师和你们对接解决这个问题。
