### ISSUE TITLE
支付宝小程序是否支持预置事件追踪？

### ISSUE THREAD

**Issue by zhuijing** [sensorsdata/sa-sdk-alipaymini#5]
只有微信小程序支持预置事件追踪吗？ 支付宝小程序是否支持 ？

[预置事件追踪](https://www.sensorsdata.cn/manual/mp_sdk.html#41-%E9%A2%84%E7%BD%AE%E4%BA%8B%E4%BB%B6%E8%BF%BD%E8%B8%AA)

**Comment by riyue** [comment]
这个功能整在排期中
