### ISSUE TITLE
频繁调用jsapi的优化建议

### ISSUE THREAD

**Issue by leiyaguang** [sensorsdata/sa-sdk-alipaymini#6]
支付宝小程序的性能体验测评有一项是`JSAPI调用次数检测`，要求`调用同一个JSAPI小于20次`。
但是目前调用`my.canIUse`来检测`my.request`是否可用的次数过多，导致性能下降。
可以将计算结果缓存，无需每次调用。
<img width="500" alt="WeChat53ba014647f7a4e8012d9f6bd9e165cf" src="https://user-images.githubusercontent.com/17355847/84493680-b784c080-acda-11ea-919d-02e3f2586f50.png">
<img width="500" alt="WeChatee3d452fcbf655c941e859f5259d3d45" src="https://user-images.githubusercontent.com/17355847/84493686-bbb0de00-acda-11ea-85a4-1b46db2a806a.png">

**Comment by riyue** [comment]
目前是一条数据出来就发送了，所以可能导致请求比较多。这个可以优化的，微信小程序做了批量发送，支付宝这个我们也开始排期做一下
