### ISSUE TITLE
支付宝全息检测提示同步jsapi调用次数过多

### ISSUE THREAD

**Issue by li-jun** [sensorsdata/sa-sdk-alipaymini#7]
在支付宝全息检测中，很多页面提示同步jsapi调用次数过多，我发现都是神策调用了setStorageSync方法，SDK能否优先一下，改用异步方法？
![Snip20220311_1](https://user-images.githubusercontent.com/1948718/157840684-4852c628-c14f-4d0f-8b2b-3281cf5ae22a.png)

**Comment by riyue** [comment]
> 在支付宝全息检测中，很多页面提示同步jsapi调用次数过多，我发现都是神策调用了setStorageSync方法，SDK能否优先一下，改用异步方法？ ![Snip20220311_1](https://user-images.githubusercontent.com/1948718/157840684-4852c628-c14f-4d0f-8b2b-3281cf5ae22a.png)

因为目前初始化时候，用户信息的存储需要同步，暂时会存在这个问题。我们会看下能否减少次数，进行优化，已经记录该需求。有问题可以继续在这里提问
